#!/usr/bin/env python3
"""Convert an image into the right-half nice!view art (widgets/my_art.c).

The art fills the screen below the battery row: 68 px wide x 140 px tall when
looking at the keyboard. Give a portrait image of that size (anything else is
scaled and cropped to fit). Dark pixels draw, light pixels stay background.

    python3 tools/nice_view_art.py path/to/image.png [--threshold 128] [--dither]
"""

import argparse
from pathlib import Path

from PIL import Image, ImageOps

WIDTH, HEIGHT = 68, 140  # portrait, as seen on the keyboard
REPO = Path(__file__).resolve().parent.parent
OUT = REPO / "boards/shields/nice_view_custom/widgets/my_art.c"


def main():
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("image")
    parser.add_argument("--threshold", type=int, default=128,
                        help="0-255; pixels darker than this draw (default 128)")
    parser.add_argument("--dither", action="store_true",
                        help="dither instead of a hard threshold, for photos")
    parser.add_argument("--invert", action="store_true", help="swap dark and light")
    parser.add_argument("--preview", help="also save the 1-bit result as a PNG here")
    args = parser.parse_args()

    img = Image.open(args.image).convert("L")
    img = ImageOps.fit(img, (WIDTH, HEIGHT), Image.Resampling.LANCZOS)
    if args.invert:
        img = ImageOps.invert(img)
    if args.dither:
        img = img.convert("1")
    else:
        img = img.point(lambda p: 255 if p >= args.threshold else 0).convert("1")

    if args.preview:
        img.save(args.preview)

    # The panel is 160x68 landscape mounted portrait: the top of the screen is the
    # panel's right edge, so rotate 90 degrees clockwise into panel orientation.
    panel = img.transpose(Image.Transpose.ROTATE_270)
    w, h = panel.size
    px = panel.load()

    # LVGL 1-bit indexed, MSB first, rows padded to whole bytes.
    # Bit 1 = light (background), bit 0 = dark (drawn), matching the stock art.
    data = []
    for y in range(h):
        for x0 in range(0, w, 8):
            byte = 0
            for bit in range(8):
                x = x0 + bit
                if x < w and px[x, y]:
                    byte |= 0x80 >> bit
            data.append(byte)

    rows = [", ".join(f"0x{b:02x}" for b in data[i:i + 15]) for i in range(0, len(data), 15)]
    body = ",\n        ".join(rows)

    OUT.write_text(f"""/*
 * Generated by tools/nice_view_art.py from {Path(args.image).name}. Do not edit by hand.
 * SPDX-License-Identifier: MIT
 */

#include <lvgl.h>

#ifndef LV_ATTRIBUTE_MEM_ALIGN
#define LV_ATTRIBUTE_MEM_ALIGN
#endif

const LV_ATTRIBUTE_MEM_ALIGN LV_ATTRIBUTE_LARGE_CONST uint8_t my_art_map[] = {{
#if CONFIG_NICE_VIEW_WIDGET_INVERTED
        0xff, 0xff, 0xff, 0xff, /*Color of index 0*/
        0x00, 0x00, 0x00, 0xff, /*Color of index 1*/
#else
        0x00, 0x00, 0x00, 0xff, /*Color of index 0*/
        0xff, 0xff, 0xff, 0xff, /*Color of index 1*/
#endif

        {body},
}};

const lv_img_dsc_t my_art = {{
    .header.cf = LV_IMG_CF_INDEXED_1BIT,
    .header.always_zero = 0,
    .header.reserved = 0,
    .header.w = {w},
    .header.h = {h},
    .data_size = {len(data) + 8},
    .data = my_art_map,
}};
""")
    print(f"wrote {OUT.relative_to(REPO)} ({w}x{h} panel, {len(data)} bytes)")


if __name__ == "__main__":
    main()
